### PR TITLE
Use Mocha, PhantomJS and TravisCI for testing

### LINKED ISSUE #155: Use a real test framework
The current tests run on an ad-hoc test runner I threw together in a couple hours, and it's been hacked to work for a variety of cases that I never anticipated from when the project was just still a small experiment.

I'd say it's time to move to something legit. Something that TravisCI can use to verify builds/PRs... something that still lets us see the output as clearly as we can now (including special characters like `\r\n` and stuff so that the diff is easy to see).

As of right now, I'm open to suggestions as to what which framework we use; I haven't made a decision yet.

### PR DESCRIPTION
**Pull request by Turbo87**
see https://travis-ci.org/Turbo87/PapaParse/builds/71137250

resolves #155

### CODE REVIEW

**Comment by mholt** [comment]
Wow! I will make it a priority to look at this today or tomorrow. Thank you!

**Comment by mholt** [comment]
Forgive me, I'm an npm newbie.

When I do `npm install` in the directory of your fork, I get this output (cruft truncated):

```
> phantomjs@1.9.17 install /Users/matt/Downloads/PapaParse-mocha/node_modules/phantomjs
> node install.js

...

Done. Phantomjs binary available at /Users/matt/Downloads/PapaParse-mocha/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.5.4 wants phantomjs@1.9.1 - 1.9.7-15

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matt/Downloads/PapaParse-mocha/npm-debug.log
```

(I'm not posting the log file here for brevity purposes.) It looks like Papa Parse requires a higher version of Phantom than what mocha allows?

**Comment by Turbo87** [comment]
@mholt see https://github.com/nathanboktae/mocha-phantomjs/commit/219bc30afa7bb629549fdff89d989e737fa67303

I've adjusted the required version ranges in the package.json file. I've also made it possible to run the `test-cases.js` completely in NodeJS, except for the tests using the File and XMLHttpRequest APIs.

**Comment by Turbo87** [comment]
i.e. try again with 212ee33 and have a look at https://travis-ci.org/Turbo87/PapaParse/builds/71154819 for the test output of both NodeJS and PhantomJS tests

**Comment by mholt** [comment]
Got it. Works like a charm. I am going to miss the way that hidden characters were printed to the screen with a different background color (made it easy to find the problem spots) but this is definitely better overall. Will set up Travis right now.

**Comment by Turbo87** [comment]
Awesome, thanks!

**Comment by bluej100** [comment]
:heart:

**Pull request merged**
