### PR TITLE
auto promise if no complete argument

### PR DESCRIPTION
**Pull request by vanodevium**
simple solution for automatic Promises

### CODE REVIEW

**Comment by dboskovic** [comment]
I wonder if there's any downside to just always returning a promise here?

**Comment by vanodevium** [comment]
@dboskovic This is because the stream is returned otherwise.

**Comment by dboskovic** [comment]
Ah right. In that case, can we add some errors if you happen to for example be using this in `step` mode which would be incompatible with the promise approach.

**Comment by vanodevium** [comment]
@dboskovic 

I'm sorry, but after re-reading the documentation, I realized that promises cannot be made here.

**Pull request closed without merging**
