### PR TITLE
Add option `forceUniformNewline`

### PR DESCRIPTION
**Pull request by pckhoi**
This will solve this issue https://github.com/mholt/PapaParse/issues/345 with files where newline character vary throughout the file. This solution isn't ideal because it will also modify quoted content. A more permanent solution might be to handle the newline character more dynamically. It seems like a huge effort to me. This solution is good enough for my need.

Please let me know how this look and I will add more tests/docs as needed.

### CODE REVIEW

**Comment by pokoli** [comment]
Hi @pckhoi,

THanks for your pull requests. Could you please fix the following issues:

- Do not modify minified file, this is done on the release process
- Could you please document the new parameter in the docs folder? 

Thanks in advance.

**Comment by pckhoi** [comment]
Shouldn't the minified file be in .gitignore then?

**Comment by pokoli** [comment]
Please keep the changes of a pull request minimum and do not include unrelated. You should not modify the gitingore nore the minified file. 

If you think we should ignore the minifed file on git please open a new issue for its discussion.

**Comment by pokoli** [comment]
I'm not sure if we should accept this PR. The reason is clear: 

The objective of PapaParse is just to *parse* but not to modify the original files. 
Is there any issue that prevents you to modify the read data before pasing it to papaparse?

**Comment by pckhoi** [comment]
This is not modifying the file, this is modifying what papaparse output. And this is an option for those who need it, the default behavior is not altered in any way.

I'm streaming the original CSV file to the browser using `chunk` callback and there's no way for me to intercept the stream before it get passed to papaparse. The CSV files are uploaded by our users and as you said, modifying the original CSV files is not an option for us.

If you still want to proceed then I will make the changes you suggested.

**Comment by pokoli** [comment]
Well the problem is that I find it too specific as we only handle the delimiters and I always prevent to have one option for each case. 
From your code I see that you replace all the delimiters to the input variable to the prefered delimiter. The input is what PapaParse gets as input and what your code passes to it so it should be a way to do this on your code without adding anything to the library. 

So I think we must reject this PR. Sorry.

**Comment by pckhoi** [comment]
I could work around this if papaparse accept [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) as input.

**Comment by pokoli** [comment]
Then it's a mather of implementing #826 which will solve most of the feature requests.

**Pull request closed without merging**
