### PR TITLE
Fast headerMap to find duplicated headers

### PR DESCRIPTION
**Pull request by dubzzz**
The current implementation used to rely on an instance of `Array` and on its `includes` method. Depending on how many headers one may have to export in the CSV this `Array` can contain many entries and performings `includes` on it might be costly as it grows (most of the cases will have to iterate over the whole collection as duplicates is rather the exception than the rule).

The current PR proposes to rely on a native Set (when available) or a simple polyfill for it. (Side note: I did not know how to put tests on the polyfill as the class is internal and never exposed so I tested it manually on my side)

Related to https://github.com/mholt/PapaParse/commit/970c1dbaab0232c8d056ce1e58dbdcb5347e2206

Please feel free to close this PR if it does not make sense for the project. And thanks a lot for papaparse!

### CODE REVIEW

**Comment by pokoli** [comment]
Hi @dubzzz 

Your pull request is very welcome!! I checked the [caniuse availability of set](https://caniuse.com/mdn-javascript_builtins_set) and it is very well supported so I think we can implement it without the pollyfil. If anyone needs the polyfill he can implement in its own code. 

Could you please remove the polifill? Thanks in advance!

**Comment by dubzzz** [comment]
Perfect I'll drop the poly fill then. And add the eslint ignore as it was complaining (target being es5)

**Comment by pokoli** [comment]
Please do not include the ignore. I updated the es target to version 6 in https://github.com/mholt/PapaParse/commit/1f6cc9c16de959f5b9778e7aaa1792d0fd27a39f
So just rebase your changes after such change.

**Comment by dubzzz** [comment]
Perfect will not put it

**Comment by dubzzz** [comment]
PR updated!

**Comment by dubzzz** [comment]
eslint seems to complain on Set 🤔

**Comment by pokoli** [comment]
@dubzzz  tests are failing, can you have a look?

**Comment by pokoli** [comment]
Seems related to https://github.com/eslint/eslint/issues/7984

**Comment by dubzzz** [comment]
Just fixed it, sorry for the force push, just changed the eslint configuration.

**Comment by pokoli** [comment]
Merged it, thank you so much for the contribution!

**Comment by dubzzz** [comment]
Thanks for the approval and for this awesome project!

**Pull request merged**
