### PR TITLE
Trim empty lines from whitespace

### PR DESCRIPTION
**Pull request by jeroenooms**
Fixes https://github.com/mholt/PapaParse/issues/285

### CODE REVIEW

**Comment by mholt** [comment]
There are tests to assert against this behavior which are now failing; I do not think this is what is intended, since technically the line is not empty.

**Comment by jeroenooms** [comment]
Do you have another suggestion to fix https://github.com/mholt/PapaParse/issues/285 ?

**Comment by mholt** [comment]
I don't think it's broken. Whitespace is not an empty line.

**Comment by jeroenooms** [comment]
Is there any way to parse a file like this then? http://web.ohmage.org/~snolen/sample_classes/01sample_class.csv It has `\r\n` linebreaks with an extra EOF. Unfortunately this input format is beyond my control.

**Comment by mholt** [comment]
You'll have to just filter those out after you get the results back, I think. Papa is a parser, not a data cleanser. Thanks for the PR though!

**Pull request closed without merging**
