### PR TITLE
return null values when dealing with empty strings (dynamictyping mode)

### PR DESCRIPTION
**Pull request by mfds**

### CODE REVIEW

**Comment by pokoli** [comment]
Hi @mfds, thanks for your pull request. 

Could you please add a test that ensures this behaviour

**Comment by mfds** [comment]
Sure, I’ll do that ASAP.

M.

**Comment by pokoli** [comment]
I've merged it. Thanks!

**Comment by mfds** [comment]
Thanks for your very fast reply :D

M.

**Pull request merged**
