### PR TITLE
Add more cases to escapeFormulae, allow to pass RegExp

### PR DESCRIPTION
**Pull request by caub**
See #796 #793

@pokoli @wcerfgba Hey guys, could you check this PR?

It adds more cases for `escapeFormulae` option, cf https://owasp.org/www-community/attacks/CSV_Injection

### CODE REVIEW

**Comment by caub** [comment]
I added possibility to pass a RegExp as `escapeFormulae` option, but not sure it's needed, just tell me, I can remove that

**Comment by pokoli** [comment]
Hi @caub!

Thanks for your suggestion. Could you please keep the current tests cases as is (so we ensure nothing is borken) and add a new test case for the regexp validation (the new feature) ?

Thanks in advance!

**Comment by caub** [comment]
Hey @pokoli 
Current changes are actually changed, https://owasp.org/www-community/attacks/CSV_Injection recommanded to escape values anyway as soon as a formulae is used

Not sure if really necessary but what's your thought? can we revert my last commit if you prefer? (and then previous tests will be identical)

**Comment by pokoli** [comment]
@caub feel free to remove some test suit if it is no longer valid (but please keep the valid ones)

**Comment by caub** [comment]
ok done, https://github.com/mholt/PapaParse/pull/904/files you can see 2 of the previous tests are affected, because  for example `=test` was converted in `'=test` as it doesn't require escaping the whole value, with owasp recommandation we get either `"'=test"` or `''=test'`

**Comment by pokoli** [comment]
Hi @caub, 

Tests failed due to node15 (which seems unrelated). I removed the version from github actions in https://github.com/mholt/PapaParse/commit/26a86fdf9f2e97225b101dad18dacdbac517ce58 

Could you please rebase the PR so I can relauch the test suite to ensure everything is in place. 

Sorry for the inconvenience.

**Comment by caub** [comment]
yep, done

**Pull request merged**
