### PR TITLE
Issue#8 Fix complete results with partial results

### PR DESCRIPTION
**Pull request by topicus**
This PR was created based on this commit b3c84bf1f1a0781e5d30fe91e44c9e23699c362b. Take a look at this and let me know if you see something wrong.

### CODE REVIEW

**Comment by bluej100** [comment]
This looks sensible to me. We'll also need to remove the logic in FileStreamer and ChunkStreamer that skips chunking if neither chunk nor step is defined.

**Comment by topicus** [comment]
Maybe I missing something but I could found that logic. Code in this PR works accumulating the results only if user does not define step nor chunk.

If user define step or chunk then results are not stored in this._completeResults. 

This is useful when you have a really big CSV and you don't want you memory blows up. 

On the other hand when you have a medium size CSV (< 500MB) handle all the file in memory make sense.

Currently FileStreamer is chunking by default and because max input length string is implementation dependant and we couldn't know how big is this value.

Anyway, probably you could give me a clue because I do not fully understand all the code yet.

**Comment by bluej100** [comment]
I'm referring to these lines on master, which deactivate streaming:

			if (!config.step && !config.chunk)
				configCopy.chunkSize = null;

Would you mind rebasing and removing those two lines? I appreciate your time.

**Comment by topicus** [comment]
Done. I've also ran the test and all passed. Let me know if you need more help.

**Comment by bluej100** [comment]
Looks great. Thank you.

**Pull request merged**
