### PR TITLE
more refactoring: StringStreamer

### PR DESCRIPTION
**Pull request by bluej100**
I'm not positive this is correct, but it feels like an improvement to me, and it passes the tests.

### CODE REVIEW

**Comment by mholt** [comment]
Hm, I'm seeing failing tests at the moment, but maybe it's just a rebase issue; the tests that are failing are ones that were introduced with recent PRs.

**Comment by bluej100** [comment]
Hmm, yup. I've pushed up a rebased patchset with fixes for those tests.

I fixed it by switching another test from complete to setTimeout, though, which is gross. How do you expect the complete callback to behave with pausing and aborting? I believe that currently, it fires immediately after aborting, which seems weird to me.

**Comment by mholt** [comment]
Complete should be executed when parsing is finished, whether aborted or not. It shouldn't be executed after pausing...

The meta object should contain an `aborted` property to indicate that parsing was aborted. But I think it's still important that complete is called when parsing is aborted so the user can get the partly-finished results.

The test "Step functions can resume parsing" seems to be failing; not sure why yet, since I've confirmed that the handle's resume function *is* being invoked and the parser is parsing the remaining input.

**Comment by bluej100** [comment]
Okay, I'll take a look. Thanks!

**Comment by bluej100** [comment]
Sorry for the delay. New patchset pushed which implements the complete callback behavior you specified and adds some more robustness to the custom test runner. Hope it meets your approval.

**Comment by bluej100** [comment]
It's kind of confusing to me that streamers and handlers can be paused separately. Might want to unify that.

**Comment by mholt** [comment]
Whew, finally got through the last big one! Thanks for all your time and effort. A lot of these issues have been thorns in my side.

Hm, what do you mean by streamers and handles being paused separately?

**Comment by bluej100** [comment]
ChunkStreamer has its own resume/pause/abort functions, which used to be in NetworkStreamer and FileStreamer. I'm guessing that no one is using them, since people don't generally construct streamers directly. We should probably either kill them or add testing and documentation.

**Comment by mholt** [comment]
I see what you mean now. I've ripped those out in a commit that's on its way. Thanks again!

**Pull request merged**
