### PR TITLE
Issue #219 Fix search quotation

### PR DESCRIPTION
**Pull request by tomothumb**
This pull request is for Issue #219 .
"String[indexer]" didn't work on IE7.
I changed to use charAt(indexer) insted of "String[indexer]".

Then, It worked.

I didn't test yet. I want you to unit test before merging them.

Thanks.

### CODE REVIEW

**Comment by mholt** [comment]
I rejected this same thing under #170 on the grounds that Papa doesn't support older browsers on purpose. Even though benchmarks and unit tests check out in FF and Chrome, I hesitate to merge this in simply to support a dead technology. Is there a reason you or your organization cannot upgrade your browser?

**Comment by tomothumb** [comment]
Oh, I didn't follow past Issue. sorry.
That's fine if you have that philosophy. I agree with you.

As a note, There are still 5% IE7 users on a certain website through Goggle analytics. I didn't ignore them then I started to fix it. It took a couple of hour to figure out the problem.
There will be someone like me.

**Comment by mholt** [comment]
Hmm. There don't appear to be any technical reasons for not merging this in, but it's more a question of where I draw the line between supporting old browsers and encouraging people to update.

I will consider it.

**Comment by tomothumb** [comment]
Official page shows supported browser. I didn't checked it on faq page...
That's my fault about try to use this on IE7.
plz forget this discussion.

It might be kind to put some information(link of solved issue / knowledge) on documentation page for legacy browser though.

Thanks

**Comment by mholt** [comment]
Naw, it's fine. :smile: I'd be happy to make browser compatibility clearer in the docs. But in the meantime, while I give this some thought, let's leave the PR open. I might still merge it in, since I'm undecided.

**Comment by mholt** [comment]
Heh, I was gonna run benchmarks one more time before merging this in and now JSPerf, my benchmarking engine, is down. :( https://github.com/jsperf/jsperf.com/issues/18

As soon as it comes back up or I change benchmark providers I will be able to verify the performance of this change and merge it in if it's fast.

**Comment by mholt** [comment]
Hmm, most of the searching I'm doing on this (now that jsPerf is back up) shows that the array index is usually a little faster than charAt, for example http://jsperf.com/array-index-vs-string-charat

And in January IE7 will officially be dead. I think I'm going to decline this PR, but thank you for submitting it! Hopefully it will continue to be useful to you.

**Pull request closed without merging**
