### PR TITLE
refactor common functionality of chunk streaming classes

### PR DESCRIPTION
**Pull request by bluej100**

### CODE REVIEW

**Comment by mholt** [comment]
If you want to rebase this with the latest master, I'll be able to more easily merge it in. Thanks!

**Comment by bluej100** [comment]
Yeah, I apologize. I'll do it soon.

**Comment by bluej100** [comment]
Rebased.

**Comment by mholt** [comment]
Definitely loving this. Nothing feels quite the same as deleting a bunch of code!

**Comment by bluej100** [comment]
Thanks! Sorry for the tedious review with all of the changes from closure variables to properties.

**Pull request merged**
