### PR TITLE
Bugfix: Resolve parsing issue when first field is empty and unquoted

### PR DESCRIPTION
**Pull request by dboskovic**
This resolves the issue mentioned in #685

### CODE REVIEW

**Comment by thomasjulianstoelen** [comment]
@dboskovic hey david just curious, how come we continue on as an empty string instead of throwing an error saying a header is missing?

**Comment by dboskovic** [comment]
There’s two layers here. One where we parse which should absolutely allow for anything in the RFC and be forgiving beyond. In this case empty data should never be a problem.

I think when you enable header mapping, we could introduce a strict mode that produces errors in the case of an empty header (or multiple identical headers) that could cause unexpected data in the end result. That said, I don’t think it’s unreasonable for there to be unlabeled columns in a dataset, so My gut says that type of validation would be better living downstream from this library.

**Comment by pokoli** [comment]
@dboskovic Thanks for the patch!

**Comment by ynicolaou** [comment]
@dboskovic this fix doesn't seem to work when using a step function. I noticed a few things that don't get parsed properly when using the step function. Any idea why is that?

**Comment by pokoli** [comment]
@ynicolaou could you plese open a new issue with some example in order to reproduce it?

**Comment by ynicolaou** [comment]
@pokoli see https://github.com/mholt/PapaParse/issues/697

**Comment by grizim** [comment]
@pokoli  - can you please publish it to NPM?

**Comment by pokoli** [comment]
I've published 5.0.2 which contains the fix.

**Pull request merged**
