### PR TITLE
avoid division by zero

### PR DESCRIPTION
**Pull request by andekande**
if preview didn't find a row, avgFieldCount will be NaN or Infinity

### CODE REVIEW

**Comment by mholt** [comment]
Hm, interesting scenario! Code looks sound, at a glance. So you tested this and it works? (I'm headed out the door so I just thought I'd ask.)

**Comment by andekande** [comment]
i have been running tests and they were green - no side effects introduced

**Comment by mholt** [comment]
Can you add a new test that causes a division by 0? That way we an assert that we don't end up breaking this accidentally later on down the road.

**Comment by andekande** [comment]
The PARSE_TESTS "Empty input string" and "Skip empty lines, with empty input" already causes this.

**Comment by mholt** [comment]
@andekande I still don't see it. Is there anything else required for reproducing it?

screen shot 2015-06-23 at 11 21 38 am

**Comment by andekande** [comment]
Well, there currently is not any fault existent. But there potentially is. Consider this:
```javascript
avgFieldCount /= preview.data.length;
 
if ((typeof bestDelta === 'undefined' || delta < bestDelta) && avgFieldCount > 1.99)
```
avgFieldCount can get "Infinity" which always is > 1.99
but this if is never hit because of the additinal bestDelta check.

The Fix is only a measure of precaution.

**Comment by mholt** [comment]
Got it. Thanks!

**Pull request merged**
