### PR TITLE
Updated double equals to triple equals, removed whitespace at end of lines and standardized quotes.

### PR DESCRIPTION
**Pull request by breck7**
Just ran the code through a linter and made some code style changes. All tests pass. Perf difference of == vs === is negligible IIRC but jsperf is currently down so don't have data at the moment.

### CODE REVIEW

**Comment by breck7** [comment]
No need to accept if you don't think this makes a difference. These are just nits :)

**Comment by mholt** [comment]
Cool, thanks. Will have to wait for jsperf to come back online to be sure about performance though. Stay tuned. :smile:

**Comment by breck7** [comment]
If the types are different === is signficantly faster, otherwise they are about equal. http://jsperf.com/triple-equals-vs-double-equals/. So this could be faster.

**Comment by mholt** [comment]
@breck7 Thanks for the info. Unfortunately it doesn't seem to be all the way online yet, all I see is:

> The get/post request has failed :(

**Comment by mholt** [comment]
@breck7 When you get a chance, sync up with master and I'll merge it in :+1:

**Pull request closed without merging**
