### PR TITLE
Added additional config option, additionalDelimitersToGuess

### PR DESCRIPTION
**Pull request by ghost**
This seemed easy enough to add in and non-intrusive to anything else, so I figured I would just create a pull request instead of opening up a feature request.

This adds an additional config option called `additionalDelimitersToGuess` where a user can pass an array of additional delimiters for PapaParse to try and guess.

For example:

```
var results = Papa.parse('"A"~"B"~"C"', {additionalDelimitersToGuess: ['~']);
results.meta.delimiter // "~"
```

I have included a couple additional tests. Please let me know if you would like more.

### CODE REVIEW

**Comment by pokoli** [comment]
Thanks for your pull request.

I think we can name it _delimitersToGuess_ and fall back to the default ones if not defined. 

Could you please document the usage of this new config parameter in the docs? They are on the docs folder of this same repository. 

Please do not modify the minified file, this is part of the release process

**Comment by astupidnerd** [comment]
@pokoli, sounds good, I can do that.

**Comment by astupidnerd** [comment]
@pokoli I've updated the pull request with those changes. Let me know if there's anything else I can do.

**Comment by nosovk** [comment]
@pokoli could you please merge it?

**Pull request merged**
