### PR TITLE
Determine global scope without using eval

### LINKED ISSUE #363: Don't use eval to determine global scope
This commit https://github.com/mholt/PapaParse/commit/fbf22867bfc6280192c5267cab84eadf50307170 use eval to determine the global scope. This will break many things (Content Security Policy is one).

Instead you can use something like this:
https://github.com/paulmillr/es6-shim/commit/2367e0953edd01ae9a5628e1f47cf14b0377a7d6

Would you be willing to make this change?

### PR DESCRIPTION
**Pull request by sandstrom**
This is makes PapaParse useable in sites where Content Security Policy is used.

Closes #363

### CODE REVIEW

**Comment by pokoli** [comment]
@sandstrom this is breaking test suit, could you fix please?

**Comment by sandstrom** [comment]
@pokoli Sorry, I don't know why this wouldn't work. AFAIK it works in a browser and node. Perhaps there is something peculiar with the test environment?

**Comment by pokoli** [comment]
@sandstrom thanks for you're patch. I have merged them manually and fixed the test with https://github.com/mholt/PapaParse/commit/ff398191f2c0547b0164e487414aec37a030bf65

**Comment by sandstrom** [comment]
@pokoli Thanks, that's awesome! ⛵️

**Pull request merged**
